# Database connections: Postgres (Supabase) when DATABASE_URL is set, else local SQLite files.
# Queries are written once with `?` placeholders in SQL both understand (ON CONFLICT, RETURNING).
# Postgres keeps each course in its own schema; SQLite keeps each course in its own file.
import atexit
import os
import sqlite3
import weakref
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

DATABASE_URL = os.getenv("DATABASE_URL", "").strip().strip("\"'").strip()  # forgive quotes/spaces pasted into a dashboard
POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))
ON_RAILWAY = bool(os.getenv("RAILWAY_ENVIRONMENT_NAME") or os.getenv("RAILWAY_PROJECT_ID"))


def require_postgres_when_hosted():
    """A hosted server must not fall back to SQLite: its disk is wiped on every deploy, so all logins and data would vanish."""
    if ON_RAILWAY and not POSTGRES:
        start = DATABASE_URL[:12] or "(empty)"
        raise RuntimeError(f"DATABASE_URL must be a Postgres URL (postgresql://...) on Railway, but it starts with {start!r}. "
                           "Set it in the service's Variables tab.")

# Schema fragments that differ between the two databases
ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
NOW = "(to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'))" if POSTGRES else "CURRENT_TIMESTAMP"

_pool = None
_search_path = weakref.WeakKeyDictionary()  # pooled connection -> schema it is set to (saves a round trip)


def _pg_pool():
    global _pool
    if _pool is None:
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool

        # autocommit: one round trip per statement instead of BEGIN + statement + COMMIT (each write is one statement)
        # prepare_threshold=None: no server-side prepared statements, which Supabase's pooler may not keep
        _pool = ConnectionPool(DATABASE_URL, min_size=1, max_size=int(os.getenv("DB_POOL_SIZE", "5")), max_idle=120,
                               kwargs={"row_factory": dict_row, "prepare_threshold": None, "autocommit": True},
                               open=True)
        atexit.register(_pool.close)
    return _pool


class _Conn:
    """The one interface callers use: execute(query, params) with `?` placeholders, and script(sql)."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, query, params=()):
        if POSTGRES:
            query = query.replace("?", "%s")
        return self._conn.execute(query, params)

    def script(self, sql):
        if POSTGRES:
            self._conn.execute(sql)  # several statements are allowed when there are no parameters
        else:
            self._conn.executescript(sql)


@contextmanager
def connect(sqlite_path, schema="public"):
    """Postgres: each statement commits on its own. SQLite: one transaction, committed when the block ends."""
    if POSTGRES:
        with _pg_pool().connection() as conn:
            if _search_path.get(conn) != schema:
                conn.execute(f'SET search_path TO "{schema}"')
                _search_path[conn] = schema
            yield _Conn(conn)
    else:
        Path(sqlite_path).parent.mkdir(exist_ok=True)
        conn = sqlite3.connect(sqlite_path)
        conn.row_factory = sqlite3.Row  # rows behave like dicts
        try:
            with conn:
                yield _Conn(conn)
        finally:
            conn.close()
